### PR TITLE
Fixes incorrectly cased filename of the Zend_Validate_Barcode_Intelli…

### LINKED ISSUE #28: Using composer >= 1.10.1 with an optimised autoloader results in a warning caused by this repository
When installing Magento 2.3.4 using composer (version 1.10.1 or higher) with the optimised autoloader flag results in this warning:

```
Deprecation Notice: Class Zend_Validate_Barcode_IntelligentMail located in ./vendor/magento/zendframework1/library/Zend/Validate/Barcode/Intelligentmail.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///composer.phar/src/Composer/Autoload/ClassMapGenerator.php:201
```

FYI: [composer version 1.10.0](https://github.com/composer/composer/releases/tag/1.10.0) started adding these warnings to prepare for composer 2.0 to be released soonish probably

If I have to guess, it's probably a case mismatch, the class is called `Zend_Validate_Barcode_IntelligentMail`, but the file is called `Intelligentmail.php`. Notice the different casing of the `M` letter.

### PR DESCRIPTION
**Pull request by hostep**
…gentMail class.

Fixes #28 

Steps to reproduce:
1) Make sure your composer version is 1.10.1 or higher
2) Clone the repository
3) Run `composer install --optimize-autoloader`
4) Notice the warning: `Deprecation Notice: Class Zend_Validate_Barcode_IntelligentMail located in ./library/Zend/Validate/Barcode/Intelligentmail.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///src/Composer/Autoload/ClassMapGenerator.php:201`
5) After applying this fix, run `composer install --optimize-autoloader`
6) Notice that the warning is gone.

### CODE REVIEW

**Comment by hostep** [comment]
@ihor-sviziev: can you try to contact somebody around this so we can move this forward?
I already contacted somebody some weeks ago on Slack but haven't heard back from them unfortunately ...

**Comment by ihor-sviziev** [comment]
@slavvka @lenaorobei @naydav could you help to move it forward?

**Comment by lenaorobei** [comment]
@magento run all tests

**Comment by lenaorobei** [comment]
@hostep thanks for this contribution. I've contacted internal team who is responsible for platform health track.

**Comment by ihor-sviziev** [comment]
@lenaorobei @sidolov @gabrieldagama any updates on this?

**Comment by lenaorobei** [comment]
For internal users, Jira task is MC-35856.
Reached out PO for prioritization.

**Comment by hostep** [comment]
Thanks @lenaorobei, not sure why it takes this long because it's a very simple fix.

Next to this, I've opened a more general composer v2 support ticket as well, since its release is steadily approaching and it would be good if Magento could support is rather sooner then later: https://github.com/magento/community-features/issues/302

**Review by rvitaliy — APPROVED** [review]

**Comment by rvitaliy** [comment]
please merge this PR and create a hotfix tag, it's a blocker for https://github.com/composer/composer/releases/tag/2.0.0
related to magento/magento2#28033

**Pull request merged**
